apiVersion: v1
kind: Service
metadata:
  name: rein
spec:
  selector:
    app: rein
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rein
  labels:
    app: rein
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rein
  template:
    metadata:
      labels:
        app: rein
    spec:
      hostname: rein
      containers:
      - name: rein
        image: docker.io/bonavadeur/rein:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: node1
---
